### ISSUE TITLE
Migrate geojson files in climate indicators tutorial data folder to geoserver

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/PAVICS-landing#26]
Accessing polygon layers via geoserver will simplify as only notebooks will need to be copied to the writable-workspace folder. Currently users must copy .ipynb and the tutorial-data subfolder to the `writable-workspace`

Can be done post upgrade to geoserver version

**Comment by Zeitsperre** [comment]
The data sets were converted to shapefile (our geoserver is too old for direct GeoJSON import) made discoverable: 
![Screenshot_2021-07-29_15-34-31](https://user-images.githubusercontent.com/10819524/127555267-74c74fcf-7632-4607-bcf6-f9b341dfb68e.png)
