### ISSUE TITLE
Missing tutorial data file

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/PAVICS-landing#89]
@tlvu I also notice that the new YML file in tutorial_data isn't transferred to the PAVICS user workspace :
https://github.com/Ouranosinc/PAVICS-landing/blob/master/content/notebooks/climate_indicators/tutorial_data/xclim_virtmodule.yml

**Comment by tlogan2000** [comment]
Is it possible that we copy only *.geojson to the jupyter user space?

**Comment by tlvu** [comment]
Is this discovered by https://github.com/Ouranosinc/PAVICS-landing/pull/88?

**Comment by tlvu** [comment]
> Is it possible that we copy only *.geojson to the jupyter user space?

Yes !  Fixing ...

**Comment by tlvu** [comment]
> > Is it possible that we copy only *.geojson to the jupyter user space?
> 
> Yes ! Fixing ...

Fixed in https://github.com/bird-house/birdhouse-deploy-ouranos/pull/23, will be live on next scheduled sync.
